---
title: <center> About Me </center>
output: html_document
---

<style>
body {text-align: justify}
</style>


Here I am, Marlon Schumacher, the owner of this homepage and I like to introduce myself. One year ago, I completed my Bachelor’s degree at the University of Stuttgart and am currently in my master’s program Empirical Political and Social Research. Especially because of the technical & statistical orientation, it had taken me from the capital Berlin to the Schwabenmetropole Stuttgart.

In the time here in Stuttgart, I have been able to expand my joy in mathematics and have discovered the statistics for me. Yes, I enjoy statistical analysis, have fun translating facts into numbers and find it nice to create appealing visualizations. In the beginning, I worked a lot with the statistical software SPSS and was able to acquire a sound knowledge there. But you quickly reach the limits with statistical software like SPSS. For some time now, I have been working intensively on the programming language R. It offers a lot of potential in terms of data analysis and visualization.

My thirst for knowledge is still not satisfied. In addition to my statistical lectures and modules, I visit numerous further education. Currently, my focus is the additional acquisition of the programming language Python and much with regard to web scraping, machine learning, Bayesian statistics and more.
Thus, I have already been able to acquire theoretical and practical experience in numerous statistical fields. I would like to share this knowledge with anyone who is interested. Because I know how many sleepless nights the statistics and especially the handling of R can bring. In addition I would like to share my own analyzes on a wide range of topics.

